//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDataAccessWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.SourcePredecessors = new HashSet<Predecessor>();
            this.TargetPredecessors = new HashSet<Predecessor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
        public System.DateTime CompletedFinish { get; set; }
        public string Assignments { get; set; }
        public int Indentation { get; set; }
        public int OrderIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predecessor> SourcePredecessors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predecessor> TargetPredecessors { get; set; }
    }
}
